import os
import subprocess

import pandas as pd
from typing_extensions import override

from germancompoundsplitting.model import Model


class MCSWrapper(Model):
    def __init__(self):
        super().__init__()
        self.name = "MCS"

    @override
    def run(self):
        prev_dir = os.getcwd()
        cur_dir = os.path.dirname(os.path.abspath(__file__))
        os.chdir(cur_dir)
        self.extract_components(self.process_compounds())
        os.chdir(prev_dir)
        return self.df

    def process_compounds(self):
        """
        Processed the compounds in the dataframe and creates lists of components in a file.
        :return: Filepath for output file containing components.
        """
        compounds_file = 'compounds.txt'
        output_label = 'components'
        output_file = compounds_file + '.' + output_label + '.SPLITS.tsv.trees'
        self.df.dropna(subset=['compounds'], inplace=True)
        self.df['compounds'].to_csv(compounds_file, header=False, index=False)
        command = 'java -jar MCS.jar --SPLIT --kmax 3 --LEMMASET Wikipedia.DE.LEMMASET.tsv --modifierMOPs Wikipedia.DE.WORDMOPs.tsv --headMOPs Wikipedia.DE.WORDMOPs.tsv --COLLECTION compounds.txt --OUTPUT components'
        try:
            with subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True) as process:
                print("MCS is processing...")
                for line in process.stderr:
                    print(line.strip())
        except FileNotFoundError as e:
            print(f"Error: {e}. File not found.")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")
        finally:
            return output_file

    def extract_components(self, output_file):
        """
        Extracts the components from the output file generated by MOP compound splitter.
        :param output_file: The file containing the processed compounds.
        """
        results = pd.read_csv(output_file, sep='\t', usecols=[4, 5], names=['compounds', 'components'])
        results.drop_duplicates(subset=['compounds'], keep='first', inplace=True)
        results['components'] = results['components'].apply(lambda x: self.split_helper(x))
        results.reset_index(drop=True, inplace=True)
        self.df['components'] = results['components']

    @staticmethod
    def split_helper(text):
        if not isinstance(text, str):
            return [Model.EXCEPTION]
        return text.split('|')


